secretGenerator:
- name: secrets
  envs:
  - secrets.env
configMapGenerator:
- name: properties
  envs:
  - properties.env
generatorOptions:
  disableNameSuffixHash: true
images:
- name: oxygen-image
  newName: log680eq16/oxygen-cs-grp01-eq16
  newTag: IMAGE_TAG
