apiVersion: v1
kind: Service
metadata:
   name: oxygen-service
spec:
  type: NodePort
  selector:
    app: oxygen-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxygen-app
  template:
    metadata:
      labels:
        app: oxygen-app
    spec:
      containers:
      - name: oxygen-app
        image: log680eq16/oxygen-cs-grp01-eq16:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: oxygen-secrets
          mountPath: /secrets
        - name: oxygen-envvars
          mountPath: /config
      volumes:
      - name: oxygen-secrets
        secret:
          secretName: oxygen-secrets-hckmfm6698
      - name: oxygen-envvars
        configMap:
          name: oxygen-envvars-tk5kcfdhg4