# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HOST: https://hvac-simulator-a23-y2kpq.ondigitalocean.app
      TOKEN: ${{ secrets.TOKEN }}
      DATABASE_SERVER_NAME: log680
      DATABASE_NAME: log-680
      USER_NAME: admin680
      USER_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      TICKETS: 2
      T_MAX: 24
      T_MIN: 19
      IMAGE_NAME: oxygen-cs-grp01-eq16

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint and stop build if there are python syntax errors or undefined names
        run: |
          pylint src/ || (echo "Linting failed" && exit 1)
      - name: Format with black
        run: |
          black src/
      - name: Test with pytest
        run: |
          pytest
      - name: Build docker image
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_RUN_NUMBER .
      - name: Deploy to DockerHub
        run: |
          docker push $IMAGE_NAME:$GITHUB_RUN_NUMBER
          docker tag $IMAGE_NAME:$GITHUB_RUN_NUMBER oxygen-cs:latest
          docker push $IMAGE_NAME:latest